modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="howlingmoonrising"

version="${mod_version}"

displayName="Howling Moon Rising"

description='''
A werewolf mod for Minecraft 1.21.1.
'''

[[dependencies.howlingmoonrising]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.howlingmoonrising]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"