modLoader="javafml"

loaderVersion="${loader_version_range}"

license="All Rights Reserved"

[[mixins]]
config="howlingmoonrising.mixins.json"

[[mods]]

modId="howlingmoonrising"

version="${mod_version}"

displayName="Howling Moon Rising"

logoFile="hm_logo.png"

authors="mareca1202"

description='''
Howling Moon Rising — A werewolf mod for Minecraft 1.21.1.
Copyright (c) 2026 mareca1202. All Rights Reserved.
'''

[[dependencies.howlingmoonrising]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.howlingmoonrising]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"